version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
        - pip install ".[dev]"
  build:
    commands:
       - pytest --cov aws_jupyter_proxy tests/unit
       - black --check .
